/**
 * Xây dựng bản đồ tính năng.
 */
export function buildFeatureMap(moduleMap) {
  const featureMap = {};
  for (const [key, info] of moduleMap) {
    const feature = info.feature || 'core';
    if (!featureMap[feature]) {
      featureMap[feature] = {
        components: [],
        hooks: [],
        stores: [],
        services: [],
        contexts: [],
        utils: [],
      };
    }
    const bucket = info.type.toLowerCase() + 's';
    const arr = featureMap[feature][bucket];
    if (arr && !arr.includes(key)) arr.push(key);
  }
  return featureMap;
}

/**
 * Xây dựng báo cáo workspace-summary.md.
 */
export function buildWorkspaceSummary(featureMap, moduleMap) {
  const byType = { Component: 0, Hook: 0, Store: 0, Service: 0, Context: 0, Utility: 0 };
  for (const [, info] of moduleMap) {
    if (byType[info.type] !== undefined) byType[info.type]++;
  }

  const lines = [];
  lines.push('# Workspace Summary');
  lines.push('');
  lines.push(`> Auto-generated by Workspace Intelligence Layer v2 — Phase 2A (AST-driven)`);
  lines.push(`> Tổng: ${moduleMap.size} modules`);
  lines.push('');
  lines.push('## Stats');
  lines.push('');
  lines.push('| Type | Count |');
  lines.push('|---|---|');
  for (const [type, count] of Object.entries(byType)) {
    if (count > 0) lines.push(`| ${type} | ${count} |`);
  }
  lines.push('');
  lines.push('---');
  lines.push('');

  const features = Object.keys(featureMap).sort();
  for (const feature of features) {
    const f = featureMap[feature];
    lines.push(`## ${feature}`);
    lines.push('');

    const printList = (label, arr) => {
      if (!arr || arr.length === 0) return;
      const names = arr.map(k => k.split(':').pop());
      const shown = names.slice(0, 15);
      const extra = names.length > 15 ? ` …+${names.length - 15}` : '';
      lines.push(`**${label}:** ${shown.join(', ')}${extra}`);
    };

    printList('Components', f.components);
    printList('Hooks', f.hooks);
    printList('Stores', f.stores);
    printList('Services', f.services);
    printList('Contexts', f.contexts);
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('## Hướng dẫn sử dụng cho Agent');
  lines.push('');
  lines.push('1. Đọc file này để nắm tổng quan project.');
  lines.push('2. Tra cứu `module-manifest.json` để xem đầy đủ metadata (imports/exports/usedBy) của một module.');
  lines.push('3. Tra cứu `feature-map.json` để tìm module theo feature.');
  lines.push('4. Tra cứu `dependency-graph.json` để biết module phụ thuộc vào đâu.');
  lines.push('5. Tra cứu `reverse-imports.json` để biết module được dùng ở đâu.');
  lines.push('6. Chỉ mở source file khi thật sự cần đọc implementation chi tiết.');

  return lines.join('\n');
}
